apiVersion: v1
kind: Service
metadata:
  name: nginx-svc 
spec:
  selector:
    app: myapp
  ports:
  - name: port1
    port: 8082
    targetPort: 80
  - name: port2
    port: 8081
    targetPort: 80
# In k8s, a svc is an abstraction that defines a logical set of Pods and a policy for accessing them. 
# It provides a stable endpoint (usually a DNS name and an IP address) to access apps in a k8s cluster, 
# even as the underlying Pods are created, deleted, or replaced.
# default svc: clusterip
# only accessible inside the cluster
# pods can comm using this static ip
# k get svc
# k port-forward service/<svc-name> <host-port>:<svc-port>
