apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - port: 8082
    nodePort: 30000
    targetPort: 80

# port range 30000 to 32767
# exposes app to the internet but is vulnerable to cyber attacks
# k get svc
# here external-ip section [i.e <none>] is the ip of the machine & internal-ip is the svc ip that can only be accessed within the cluster
# use loadbalancer instead 
